### ISSUE TITLE
Automatically create RBAC rules for users to create claims when defining XRDs

### ISSUE THREAD

**Issue by ccremer** [vshn/component-appcat#13]
## Context

Currently, `pkg.appcat.composite.objectstorage` defines explicitly 2 cluster roles so that users can create claims in namespaces.
In the component via jsonnet, we could create those rules automatically, removing the need to maintain these roles separately.

## Alternatives

* Keep it as of v0.1.1
* Use Crossplane's RBAC management policy = All, but that completely changes how RBAC is done, see #12

**Comment by Kidswiss** [comment]
Isn't this implemented with https://github.com/vshn/component-appcat/pull/7/commits/85b99cc64e5d7fa8bba522c2dd9bd10b2c4555fc ?

**Comment by ccremer** [comment]
yes
