### ISSUE TITLE
Generate the XRDs using Go structs with KubeBuilder

### ISSUE THREAD

**Issue by ccremer** [vshn/component-appcat#15]
## Context

Problem:
The XRD spec contains an API scheme (parameters, status etc) that is pretty much native Kubernetes OpenAPI scheme. Manually maintaining this scheme is error prone. I've looked around and didn't find a tool in https://openapi.tools/ that covers the case at hand.

Idea:
Kubernetes Operators today are built with Kubebuilder, a code generator for building CRDs. The CRDs also follow the OpenAPI scheme.
We could setup some boilerplate and setup the Types and Fields in Go structs (see https://github.com/vshn/provider-cloudscale/blob/f68758cc396358852ba09a0c9ff3b5a3ad877521/apis/cloudscale/v1/bucket_types.go) and let KubeBuilder/`go generate` generate the API.
That creates a CRD though, but with some yq/Go/jsonnet magic we can basically copy the generated scheme from the CRD into the XRD.

## ACs

* Setup Go code to generate a CRD using Kubebuilder (see example: https://github.com/vshn/provider-cloudscale/blob/master/apis/generate.go and related subdirectory)
* Once the CRD is created, merge/copy the OpenAPI scheme from the CRD (`.spec.versions[*]`) to the composite (`.spec.versions[*]`)
  * maybe with `yq` or a small Go script
* GitHub action that aborts a check when the generated composition is out-of-date.

**Comment by Kidswiss** [comment]
Go-Swagger can create openapi from code: https://goswagger.io/use/spec/model.html

But it will also generate a lot of other stuff we don't need. So going through kubebuilder seems the better option IMHO.

**Comment by ccremer** [comment]
I would only consider KubeBuilder, as that's the only generator that pretty much guarantees a scheme that Kubernetes understands. (for example, special flags for type handling, see https://book.kubebuilder.io/reference/markers/crd-processing.html)

As we've built a bunch of Operators by now, we have plenty of experience with Kubebuilder, so the initial setup should be fairly easy.

**Comment by ccremer** [comment]
First implementation done, see https://github.com/vshn/component-appcat/blob/cef1e368fd00d0b848052b904066c43b4ad2ad69/apis/v1/objectstorage_types.go as an example
