### ISSUE TITLE
Get rid of the namespace observer exoscale

### ISSUE THREAD

**Issue by Kidswiss** [vshn/component-appcat#35]
## Context

Currently, for the ObjectBucket XRD and composition we use provider-kubernetes and its Object resource to watch the namespace of the claims. We need that to figure out the APPUiO Cloud organization name for billing purposes (see more: https://kb.vshn.ch/appuio-cloud/references/architecture/metering-data-flow.html). This organization information is in the namespace labels where the claim resides.

The current approach is to copy that `appuio.io/organization` label to the managed resource, so that the metrics collectors can pick up this information from the managed resources.

### Idea

it may be beneficial if the metrics collector directly query the Kubernetes API and figure out this namespace label themselves. We reduce complexity of the compositions, but only slightly increase complexity in the metrics collector. The collectors would have to simply GET the namespace objects for each managed resource. 

### Impact
* exoscale-metrics-collector already has the plumbing for querying Kubernetes API. Adding a query for the namespace should be trivial
* The composition no longer provision provider-kubernetes Object resources

## Out of Scope

* Commodore component does not need to be updated yet.

## Alternatives

Continue using the current watch-and-patch approach.

## Acceptance Criteria

* Extend exoscale-metrics-collector with listing Namespaces
* Adjust composition so that it doesn't use provider-kubernetes anymore (and stops patching the ns label in managed resource)
* Test out the composition and collector on our Lab cluster

**Comment by susana-garcia** [comment]
@Kidswiss a question: does this apply only to ObjectBucket XRD or to the DBaaS objects as well?

**Comment by Kidswiss** [comment]
I think the DBaaS collection also relies on this, so we probably have to touch them to. @mweibel @ZuGao correct me if I'm wrong.

When this issue was created, we didn't yet have the DBaaS collection :)

**Comment by ZuGao** [comment]
Yes, the changes has to be made for both objectostorage and dbaas.

**Comment by susana-garcia** [comment]
that's what I thought, but I just wanted to double checked, thank you both
