### ISSUE TITLE
Broken image reference in explanation `Manage secrets not coming from a provider`

### ISSUE THREAD

**Issue by simu** [vshn/component-appcat#85]
Original report in https://github.com/projectsyn/component-hub/issues/68 by @arska:

> https://hub.syn.tools/appcat/explanations/crossplane-secrets-non-provider.html references an image at https://hub.syn.tools/appcat/_images/crossplane-secrets.png which does not exist. The original https://github.com/vshn/component-appcat/blob/master/docs/modules/ROOT/pages/explanations/crossplane-secrets-non-provider.adoc references the image at https://github.com/vshn/component-appcat/raw/master/docs/modules/ROOT/pages/explanations/crossplane-secrets.png where it does exist.

## Reproduce

* Run the local preview with `make docs-serve`
* Navigate to http://localhost:2020/appcat/explanations/crossplane-secrets-non-provider.html

## Actual Behavior

Image reference in the rendered documentation page (https://hub.syn.tools/appcat/explanations/crossplane-secrets-non-provider.html) is broken.

## Expected Behavior

Image is displayed in the rendered documentation page. Please note that Antora expects images to be present in `docs/modules/ROOT/assets/images` and not alongside the Asciidoc pages, see e.g. https://github.com/vshn/billing-collector-cloudservices/

**Comment by wejdross** [comment]
https://github.com/vshn/component-appcat/pull/209

**Comment by wejdross** [comment]
fixed with #209
